Repository yodaos-project/yoda.js, pull requests merged in 2019-09, with the labels that each got.

#876 build: use clang-format nom package
  package.json
  packages/@yodaos/speech-synthesis/src/speech-synthesizer.cc
  tools/apt-get-install-deps.sh
Labels: build

#873 lightd: do not init prepared audio if `player.lightd.holdcon` is 0
  runtime/services/lightd/index.js
Labels: backport-to-v7.x, light

#877 build: use clang-format nom package
  package.json
  packages/@yoda/flora/src/cli-native.cc
  tools/apt-get-install-deps.sh
Labels: v7.x

#875 app-scheduler: generate coredump on ANR
  runtime/app/app-bridge.js
  runtime/app/default-launcher.js
  runtime/app/executable-launcher.js
  runtime/component/app-scheduler.js
Labels: scheduler

#874 fix crash that caused by uncatch error
  apps/cloudappclient/app.js
Labels: v7.x

#884 test: disable the httpdns tests
  test/testsets.txt
Labels: test

#882 turen: fix the invalid flora args on recoverPausedOnAwaken()
  runtime/lib/component/turen.js
  test/component/turen/reset-awaken.test.js
Labels: author ready, v7.x

#883 pony: save application report in app data dir
  packages/@yoda/oh-my-little-pony/index.js
  runtime/client/ext-app-entry.js
  runtime/client/ext-helper.js
Labels: author ready, backport-to-v7.x, report

#886 chore: cleanup unused files and refine docs
  docs/README.md
  docs/configure-ota.md
  docs/get-started-with-native-app.md
  etc/yoda/component-config.json
  runtime/lib/performance.js
  runtime/probe.json
Labels: docs

#888 media: add recovery.mp3 and a readable readme for system developers
  cmake/yodart.cmake
  res/media/README.md
  res/media/recovery.mp3
Labels: docs

#887 pony: backport #883 into v7.x-staging partially
  packages/@yoda/oh-my-little-pony/index.js
  packages/@yoda/util/fs.js
  test/@yoda/oh-my-little-pony/executor.js
  test/@yoda/oh-my-little-pony/index.test.js
  test/@yoda/oh-my-little-pony/stacktrace.js
  test/testsets-local.txt
Labels: v7.x
